import React from 'react';

export default function AISummaryBox({ data, loading }) {
  if (loading) {
    return (
      <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 animate-pulse h-64 flex flex-col justify-center items-center">
        <div className="text-indigo-500 font-medium">Generating AI Brief...</div>
        <div className="text-xs text-gray-400 mt-2">Analyzing 8.5k rows</div>
      </div>
    );
  }

  // If no data yet or error
  if (!data) return null;

  return (
    <div className="bg-white p-5 rounded-xl shadow-sm border border-indigo-50 relative overflow-hidden">
      {/* Decorative background accent */}
      <div className="absolute top-0 right-0 w-20 h-20 bg-indigo-50 rounded-bl-full -mr-10 -mt-10 opacity-50 pointer-events-none"></div>

      <div className="flex items-center gap-2 mb-4 relative z-10">
        <span className="text-xl">✨</span>
        <h3 className="font-bold text-gray-800 text-lg">AI Intelligence Brief</h3>
      </div>
      
      {/* Headline */}
      <div className="font-bold text-indigo-700 text-md mb-3 leading-tight relative z-10">
        {data.headline || "Dataset Analysis"}
      </div>

      {/* Main Summary */}
      <p className="text-sm text-gray-600 leading-relaxed mb-4 relative z-10 border-l-2 border-indigo-200 pl-3">
        {data.summary}
      </p>

      {/* Evidence / Bullet points */}
      {data.evidence && data.evidence.length > 0 && (
        <div className="bg-gray-50 p-3 rounded-lg relative z-10">
          <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2">Key Signals Found</p>
          <ul className="space-y-1">
            {data.evidence.map((item, i) => (
              <li key={i} className="text-xs text-gray-700 flex items-start gap-2">
                <span className="text-indigo-400 mt-0.5">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
      
      <div className="mt-3 text-[10px] text-gray-400 text-right">
        Generated by SimPPL AI based on {data.evidence ? "smart sampling" : "current filters"}
      </div>
    </div>
  );
}